### ISSUE TITLE
Opt[] is not producing None values

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#10]
Seems like operations like map() are not rerun when the value changes to None. That is according to Option.map probably (but then the parameter type should not be Option), but a bit unexpected when all other operations now uses Option[].

**Comment by tindzk** [comment]
Perhaps I misunderstood your description, but it works for me. See the referenced test case above.

**Comment by mkotsbak** [comment]
Ok, probably a red herring. I have problems with combine() where one part was Opt, but it is not recalculated on changes in both Vars.
