### ISSUE TITLE
Support for combining read channels

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#11]
StateChannel.combine works fine, but it does not work when combining derived channels like:

val user = Opt[User](..)
val isLoggedIn = user.isDefined

val combined = isLoggedIn.combine(someOtherChannel)

Is there any reason why it could not work?

**Comment by tindzk** [comment]
Yes, because we need access to its contents. That's why it takes a ``StateChannel``. Otherwise, we'd need to cache the values of the channel, which would lead to a higher memory consumption. Perhaps we can design it in a better way. What would you suggest?

**Comment by mkotsbak** [comment]
This is solved in 17ccecb69c9a6e4415322fef77bfffadc270f10f.
