### ISSUE TITLE
Add isDefinedAndIs(T) to Opt

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#13]
Opt has isDefined() and inherited is(). I see I often combine that, so I would like to have something like:

def isDefinedAndIs(someValue: T) = {
  map(_.isDefined && _.get == someValue)
}

**Comment by tindzk** [comment]
How do you like ``valueIs()``?

**Comment by mkotsbak** [comment]
That is probably better.

In the mean time, a workaround that seems to work is to use Opt.is( Some(value) ).

**Comment by tindzk** [comment]
After thinking about it, we should name it ``contains()`` instead (in analogy to ``Option.contains``).

**Comment by mkotsbak** [comment]
True. As it is essentially wrapping Option too.
