### ISSUE TITLE
Support for zip() for more than 2 input channels

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#18]
ch1.zip(ch2).zip(ch3) is giving a nested tuple, which is a bit ugly to e.g. match on:

ch1.zip(ch2).zip(ch3).map {
  case ((ch1Val, ch2Val), ch3Val) =>
...
}

Instead, zip should allow multiple arguments:

ch1.zip(ch2, ch3) and it should give a triple:

ch1.zip(ch2, ch3).map {
case (ch1Val, ch2Val, ch3Val) => 
...
}

See. also #19

**Comment by mkotsbak** [comment]
Or maybe support some flattening or flatZip?

**Comment by tindzk** [comment]
To my knowledge variable-length tuples are not possible. How do other projects solve this?

**Comment by mkotsbak** [comment]
Hmm, if it isn't, maybe hard coding zip with e.g. 2, 3 and 4 arguments would be a workaround.

**Comment by mkotsbak** [comment]
For more arguments maybe use a list?

**Comment by mkotsbak** [comment]
I'm suspecting Slick might have been in this issue.

**Comment by mkotsbak** [comment]
Hmm, but monadic style is supported:

This:
.show(initial.zip(headword).map { case (init, head) => init && head.length == 0})

could be written as:

.show(initial.flatMap(init => headword.is("").map(noHead => noHead && init)))

**Comment by mkotsbak** [comment]
Looking at Bacon.js: https://baconjs.github.io/api.html#bacon-combinewith

Combinewith is probably possible to implement in Scala too, with both input channels and arguments to the combining function as varargs?

The array variant is similar to my List suggestion.

**Comment by mkotsbak** [comment]
Looking into a hardcoded version for 3 arguments.
