### ISSUE TITLE
Add aritmetic operations for channels with numeric types

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#20]
Similar to #9, e.g. ReadChannel[Int] should have:

val ch1 = Var(1)
val ch2 = Var(2)

val 3 = ch1 + ch2

which implicitly calls map.

**Comment by mkotsbak** [comment]
All common operations on common T types should ideally be supported, at least those involving two instances as long as they do not interfer with operations that the channes should handle.

What I can think of else is string operations like '+'.  Maybe some less common ones should be placed in separate package for selective import support.

**Comment by mkotsbak** [comment]
The toInt, toDouble etc. would also be useful to have on these types. Unfortunately it seems Scala type hierarchy does not have a common type for all numeric types...

**Comment by tindzk** [comment]
You can use the `Numeric` trait. See [this link](http://stackoverflow.com/questions/10160280/how-to-implement-generic-average-function-in-scala) for an example.

**Comment by mkotsbak** [comment]
Ah nice! I hope it also works into a ReadChannel. Scala is awesome!

**Comment by mkotsbak** [comment]
Seems like so in the examples. And I think Fractional is better, so we could have division operator too.

**Comment by tindzk** [comment]
But if you use `Fractional`, it will not work for integers.

**Comment by mkotsbak** [comment]
I suspect we should support both. Just tested that Numeric works fine with + for Int.

**Comment by tindzk** [comment]
Yes, that makes sense.
