### ISSUE TITLE
Support zipped / zipWith

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#25]
Separating out this issue from PR: https://github.com/MetaStack-pl/MetaRx/pull/24 and issue #24 

tindzk: "My suggestion:

zipWith[U, V](other: ReadChannel[U], f: (T, U) => V): ReadChannel[V]
"

mkotsbak:

"Hmm, sometimes the type interference does not impress much. With the signature above, this:

val ch = Var(3)
val ch2 = Channel[Int]()

val sum = ch.zipWith(ch2, _ + _)

fails with: missing parameter type for expanded function ((x$20: Int, x$21) => x$20.$plus(x$21))

This works fine:

def zipWithU: ReadChannel[U] = {
zip(other) map (z => f(z._1, z._2))
}

Having both for type interferencer gives "have same type after erasure: (other: pl.metastack.metarx.ReadChannel, f: Function2)pl.metastack.metarx.ReadChannel" so maybe we should add both with different names?"

From Gitter chat:
tindzk: "A similar function was planned for Scala: http://stackoverflow.com/a/1157684 Would you prefer zipped?
val out: ReadChannel[Int] = (ch1, ch2).zipped.map(_ + _)
I don't think this is a good solution because we'll end up with even more implicit conversions."

tindzk: "There is a workaround for the type inference issue: You can specify a second parameter list. This will infer the type correctly:

zipWith[U, V](other: ReadChannel[U])(f: (T, U) => V): ReadChannel[V]"

**Comment by tindzk** [comment]
Implemented in https://github.com/MetaStack-pl/MetaRx/commit/a05c11828401504d8524baf99dbc8e4bad94d93b.

**Comment by mkotsbak** [comment]
I will update the operator code to use this.

Was too lazy to add scala blocks, as the character is hard to type :)
