### ISSUE TITLE
Support for different map-ing if Opt has value or not

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#3]
It should be possible to supply two map functions, one if the Opt contains any value, and another one if it does not. Similar to what is possible with scala.Option.fold (with a better name). Opt.toOption probably won't make it reactive, as it just gives the cached value.

Use case in Widok (wizard steps that depends on the previous):

def userOperation(u: User) = span(
  p("First name", u.firstName)
...
)

div(
    selectedUser.fold(
        => span(), // empty
        userOperation)
)

**Comment by mkotsbak** [comment]
Workaround:
selectedUser.values.map {
            case Some(u: User) => userOperation(u)
            case None => span()
        }

But then the user is not reactively connected, so the parameter should instead be Channel[User]:

def userOperation(u: Channel[User]) = span(...

**Comment by tindzk** [comment]
We could add a function ``mapOrElse(userOperation, span())``.

**Comment by mkotsbak** [comment]
Yes, I like that name better than fold().
