### ISSUE TITLE
Support operators for Opt

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#39]
The operators like &&, +, - are defined for ReadChannel. Even though Opt derives from that one, it does not work.

I guess that would be solved by bug #31, and also bug #33 with a solution where map() works only on existing values.

**Comment by tindzk** [comment]
What should `Opt[Int]() * 2` yield? Do you have any specific use case in mind?

**Comment by mkotsbak** [comment]
It should yield 2 * the value if defined, else None.

**Comment by mkotsbak** [comment]
An use case, currency calculator, where sourceCurrency is specified by the user:

```scala
val sourceCurrency: Opt[Float]
val currencyRate = 1.053
val destinationCurrency = sourceCurrency * currencyRate
```

The result should be empty without any input.
