### ISSUE TITLE
Support for json serialization

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#4]
Would be nice if Vars could be serialized to and from json using some library like upickle or circe.

**Comment by mkotsbak** [comment]
See also https://github.com/travisbrown/circe/issues/41

**Comment by tindzk** [comment]
As for uPickle, it should be fairly easy to implement. Have a look at [these implicits](https://github.com/lihaoyi/upickle-pprint/blob/master/upickle/shared/src/main/scala/upickle/Implicits.scala#L150). MetaRx currently has no dependencies and I'm not sure I want to pull in a serialisation library.

**Comment by mkotsbak** [comment]
Ah ok. It should probably be in a separate library to pull into dependencies if you use both.

**Comment by tindzk** [comment]
Implemented in d5beeb614e8df7679312d1a3068a1fefddd4b772.

**Comment by mkotsbak** [comment]
Great!
