### ISSUE TITLE
Cycles after failed removal from Buffer

### ISSUE THREAD

**Issue by andriyvnester** [MetaStack-pl/MetaRx#59]
```scala
val buf = Buffer[String]
buf ++= Seq("green", "blue")
buf -= "red" // java.lang.AssertionError: assertion failed: remove() with invalid position
```
After failed removal from a buffer, next interactions with it like `buf += "red"` or `buf.clear()` cause `java.lang.AssertionError: assertion failed: Cycle found`

I know you could check whether buffer contains the item before removing it, but still this doesn't look like expected behavior.

**Comment by tindzk** [comment]
Thanks for reporting!
