### ISSUE TITLE
Publish scaladoc for library

### ISSUE THREAD

**Issue by benjaminfrank** [MetaStack-pl/MetaRx#60]
Hi,

I am looking for the scaladoc of MetaRx, does this exist somwhere?

**Comment by mkotsbak** [comment]
I guess that must be Channel: https://github.com/MetaStack-pl/MetaRx/blob/master/shared/src/main/scala/pl/metastack/metarx/Channel.scala

**Comment by mkotsbak** [comment]
Please change the title of the issue to something like "Publish scaladoc for library". Questions are better asked in Gitter room: https://gitter.im/MetaStack-pl/MetaRx?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by benjaminfrank** [comment]
Thanks for your reply. Changed title as requested and adjusted my question.

**Comment by tindzk** [comment]
Sorry for the delay! The ScalaDocs documentation is available [here](https://www.javadoc.io/doc/pl.metastack/metarx_2.11/).
