### ISSUE TITLE
Add support for throttling

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#7]
It would be nice to have support for throttling channels as with Bacon.Js: https://github.com/baconjs/bacon.js/#observable-throttle

One use case would be completion/validation of fields where throttling could improve client performance and reduce server load.

**Comment by tindzk** [comment]
For this we'll have to implement something similar to [Monifu's schedulers](https://github.com/monifu/monifu/wiki/Schedulers) to be compatible with JVM and Scala.js.

Another combinator that could be useful in this context would be `delay()` (see also [ticket #15 in Widok] (https://github.com/widok/widok/issues/15)).
