### ISSUE TITLE
Support for finding and updating element(s) in BufSet

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#8]
If you want to update an element in a Buffer, find() only returns the element, and update() needs the index.

I want something like findAndUpdate(query: T => Boolean, newElement: T)

**Comment by tindzk** [comment]
[``update()``](https://github.com/MetaStack-pl/MetaRx/blob/master/shared/src/main/scala/pl/metastack/metarx/Buffer.scala#L658) doesn't take an index, but a function ``T => T``. This should be exactly what you need?

**Comment by mkotsbak** [comment]
Sorry, I'm using a BufSet.
