### ISSUE TITLE
Add support for and-operator between channels

### ISSUE THREAD

**Issue by mkotsbak** [MetaStack-pl/MetaRx#9]
There is ReadChannel.or(), but why not ReadChannel.and()?

Workaround is probably to do a map() instead.

**Comment by tindzk** [comment]
What is ``and()`` supposed to do?

**Comment by mkotsbak** [comment]
Good question. I guess or is merge. I would like it to be a && operator for Channel[Boolean] as an easier alternative to combine().

**Comment by tindzk** [comment]
Well, I'm thinking how to make it fit well into the API. ``a.or(b)`` produces ``()`` when there is a change on ``a`` or ``b``. So ``and`` should be the opposite, but I'm not sure what it should exactly do. It definitely should not return ``ReadChannel[(T, U)]`` as ``combine()`` does.

I think what you are looking for is ``zip``, which is implemented for all state channels. Have you tried it out?

**Comment by mkotsbak** [comment]
Tried this:

  implicit class ReadChannelEx(rch: ReadChannel[Boolean]) {
    def &&(other: ReadChannel[Boolean]): ReadChannel[Boolean] =  {
      rch.flatMap (thisVal => other.map(otherVal => thisVal && otherVal) )
    }

    def ||(other: ReadChannel[Boolean]): ReadChannel[Boolean] =  {
      rch.flatMap (thisVal => other.map(otherVal => thisVal || otherVal) )
    }
  }

but it does not seem to work...

**Comment by mkotsbak** [comment]
Could we just put this into metarx.scala and maybe call it "ReadChannelBooleanExtensions"?

**Comment by mkotsbak** [comment]
Operator ! should also be added, and maybe also isTrue which returns a ReadChannel[Unit]:

        def isTrue = rch.map(_)
        def ! = rch.map(value => !value)

**Comment by mkotsbak** [comment]
Lets add comparing with Booleans too:

```scala

    implicit class ReadChannelBooleanExtensions(rch: ReadChannel[Boolean]) {
        def &&(other: ReadChannel[Boolean]): ReadChannel[Boolean] =  {
            rch.flatMap (thisVal => other.map(otherVal => thisVal && otherVal) )
        }
        def &&(argument: Boolean): ReadChannel[Boolean] = {
            rch.map(value => value && argument)
        }

        def ||(other: ReadChannel[Boolean]): ReadChannel[Boolean] =  {
            rch.flatMap (thisVal => other.map(otherVal => thisVal || otherVal) )
        }
        def ||(argument: Boolean): ReadChannel[Boolean] = {
            rch.map(value => value || argument)
        }

        def isTrue = rch.map(_ == true)
        def unary_! = rch.map(value => !value)
    }

```
